version: 0.2

env:
    variables:

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo "Capturing the AWS CLI and Python versions used in this build."
            - aws --version
            - python --version
    pre_build:
        commands:
    build:
        commands:
            - echo Build started on `date`
            - zip -r -j hw2_1323_lambda1.zip src/hw2_lambda1.py src/util.py src/s3.py
            - zip -r -j hw2_1323_lambda2.zip src/hw2_lambda2.py
    post_build:
        commands:
            - echo Build completed on `date`
            - echo "Updating lambda function code."
            - aws lambda update-function-code --function-name "hw2_lambda1" --zip-file fileb://./hw2_1323_lambda1.zip
            - aws lambda update-function-code --function-name "hw2_lambda2" --zip-file fileb://./hw2_1323_lambda2.zip

artifacts:
    name: hw2_1323_lambda_build
    discard-paths: yes