version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo Capturing the AWS CLI and Python versions used in this build
            - aws --version
            - python --version
    pre_build:
        commands:
            - echo Nothing to do in the pre_build phase.
    build:
        commands:
            - echo Starting the build phase on `date`
            - zip -r sample_lambda.zip sample_lambda.py sts.py

    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - sample_lambda.zip
    name: sample_lambda-build