version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo Capturing the AWS CLI and Python versions used in this build
            - aws --version
            - python --version
    pre_build:
        commands:
            - echo Nothing to do in the pre_build phase.
    build:
        commands:
            - echo Starting the build phase on `date`
            - zip -r lambda_function_1.zip src/lambda_function_1.py src/s3.py src/sts.py src/util.py
            - zip -r lambda_function_2.zip src/lambda_function_2.py src/s3.py src/sts.py src/util.py
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - lambda_function_1.zip
        - lambda_function_2.zip
    name: assignment2-build