version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo Capturing the AWS CLI and Python versions used in this build
            - aws --version
            - python --version
    pre_build:
        commands:
            - echo Nothing to do in the pre_build phase.
    build:
        commands:
            - echo Starting the build phase on `date`
            - cd src
            - zip -r hw2_1323_lambdas.zip *.py
            - zip -r hw2_1323_lambda1.zip hw2_lambda1.py s3.py util.py
            - zip -r hw2_1323_lambda2.zip hw2_lambda2.py
            - zip -r hw2_1323_lambda3.zip hw2_lambda3.py
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - hw2_1323_lambdas.zip    # Python code for all lambdas in one zip file
        - hw2_1323_lambda1.zip    # Only python code for lambda 1
        - hw2_1323_lambda2.zip    # Only python code for lambda 2
        - hw2_1323_lambda3.zip    # Only python code for lambda 3
    name: hw2-1323_lambda-build