version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo Capturing the AWS CLI and Python versions used in this build
            - aws --version
            - python --version
    pre_build:
        commands:
            - echo Nothing to do in the pre_build phase.
    build:
        commands:
            - echo Starting the build phase on `date`
            - zip -r hw2_dd2676_lambda_functions.zip src/*.py
            - zip -r hw2_dd2676_lambda_function1.zip src/lambda_function_1.py src/s3.py src/util.py
            - zip -r hw2_dd2676_lambda_function2.zip src/lambda_function_2.py src/s3.py src/util.py
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - hw2_dd2676_lambda_functions.zip
        - hw2_dd2676_lambda_function1.zip
        - hw2_dd2676_lambda_function2.zip
    name: hw2-dd2676_lambda-build