version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo "Capturing the AWS CLI and Python versions used in the build."
            - aws --version
    pre_build:
        commands:
    build:
        commands:
            - echo Build started on `date`
            - aws apigateway get-sdk --rest-api-id d8n5fb21w7 --stage-name v1 --sdk-type javascript hw2-js-sdk.zip
    post_build:
        commands:

artifacts:
    files:
        - hw2-js-sdk.zip