version: 0.2
phases:
    install:
        commands:
            - echo "Capturing the AWS CLI version used in the build."
            - aws --version
    build:
        commands:
            - echo Generating hw2 javascript sdk - started on `date`
            #- api_id=$(aws apigateway get-rest-apis --query 'items[?name==`hw2-api-gateway`].[id]' --output text)
            - aws apigateway get-sdk --rest-api-id d3kgjj3nx4 --stage-name v1 --sdk-type javascript hw2-js-sdk.zip
    post_build:
        commands:
artifacts:
    files:
        - hw2-js-sdk.zip

# REFERENCES:
#
#   - Build specification reference for CodeBuild
#     https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
#
#   - AWS API Gateway CLI Command Reference v2
#     https://awscli.amazonaws.com/v2/documentation/api/latest/reference/apigateway/index.html


