version: 0.2
phases:
    install:
        commands:
            - echo "Capturing the AWS CLI version used in the build."
            - aws --version
    build:
        commands:
            - echo Generating hw2 javascript sdk - started on `date`
            - aws apigateway get-sdk --rest-api-id d8n5fb21w7 --stage-name v1 --sdk-type javascript hw2-js-sdk.zip
    post_build:
        commands:
artifacts:
    files:
        - hw2-js-sdk.zip

# REFERENCE:
#   - Build specification reference for CodeBuild
#     https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
