AWSTemplateFormatVersion: "2010-09-09"
Description: 'Creates Homework #2 Code Pipeline'
Resources:

  HW2RepoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hw2-1323-repo
      Tags:
        - Key: project
          Value: hw2
        - Key: account
          Value: 1323

Outputs:
  HW2RepoBucketARN:
    Description: 'Output the ARN for the new hw2-1323-repo bucket'
    Value: !GetAtt HW2RepoBucket.Arn
