AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates lambda functions used for Homework #2"
Resources:

  HW2PhotosBucket:
    # Source: https://www.itonaut.com/2018/10/03/implement-s3-bucket-lambda-triggers-in-aws-cloudformation/
    Type: AWS::S3::Bucket
    DependsOn: HW2LambdaFunction1Permission
    Properties:
      BucketName: hw2-dd2676-photos
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt HW2LambdaFunction1.Arn
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .jpeg
      Tags:
        - Key: project
          Value: hw2
        - Key: student
          Value: dd2676

  HW2LambdaFunction1Permission:
    # Source: https://www.itonaut.com/2018/10/03/implement-s3-bucket-lambda-triggers-in-aws-cloudformation/
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref HW2LambdaFunction1
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::hw2-dd2676-photos'
      SourceAccount: !Ref AWS::AccountId

  HW2LambdaFunctionExecutionRole:
    # Source: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-tags
    Type: AWS::IAM::Role
    Properties:
      RoleName: hw2-dd2676-lambda-function-execution-role
      Description: Describe this IAM role here
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: '/'
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: logs:*
            Resource: arn:aws:logs:*:*:*

  HW2LambdaFunction1:
    # Source: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
    Type: AWS::Lambda::Function
    Properties:
      Description: Describe your lambda function here
      FunctionName: hw2_lambda1
      Runtime: python3.8
      Role: arn:aws:iam::677126791323:role/viens-lambda-service-role
      Code:
        S3Bucket: hw2-dd2676-repo
        S3Key: hw2-dd2676_lambda-build/hw2_dd2676_lambda1.zip
      Handler: hw2_lambda1.lambda_handler
      MemorySize: 256
      Timeout: 10
      Tags:
        - Key: project
          Value: hw2
        - Key: student
          Value: dd2676

  HW2LambdaFunction2:
    # Source: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
    Type: AWS::Lambda::Function
    Properties:
      Description: Describe your lambda function here
      FunctionName: hw2_lambda2
      Runtime: python3.8
      Role: arn:aws:iam::677126791323:role/viens-lambda-service-role
      Code:
        S3Bucket: hw2-dd2676-repo
        S3Key: hw2-dd2676_lambda-build/hw2_dd2676_lambda2.zip
      Handler: hw2_lambda2.lambda_handler
      MemorySize: 256
      Timeout: 10
      Tags:
        - Key: project
          Value: hw2
        - Key: student
          Value: dd2676

  HW2LambdaFunction3:
    # Source: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
    Type: AWS::Lambda::Function
    Properties:
      Description: Describe your lambda function here
      FunctionName: hw2_lambda3
      Runtime: python3.8
      Role: arn:aws:iam::677126791323:role/viens-lambda-service-role
      Code:
        S3Bucket: hw2-dd2676-repo
        S3Key: hw2-dd2676_lambda-build/hw2_dd2676_lambda3.zip
      Handler: hw2_lambda3.lambda_handler
      MemorySize: 256
      Timeout: 10
      Tags:
        - Key: project
          Value: hw2
        - Key: student
          Value: dd2676

Outputs:
  HW2PhotosBucketARN:
    Description: 'The ARN for the hw2-dd2676-photos bucket'
    Value: !GetAtt HW2PhotosBucket.Arn
  HW2LambdaFunctionExecutionRoleARN:
    Description: 'The ARN for the lambda function execution role'
    Value: !GetAtt HW2LambdaFunctionExecutionRole.Arn

