AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates AWS Resources for Homework #2"

Parameters:

  DomainName:
    Type: String
    Description: User-defined OpenSearch domain name
    Default: hw2-opensearch-domain

  EngineVersion:
    Type: String
    Description: User-defined OpenSearch version
    Default: OpenSearch_1.0

  InstanceType:
    Type: String
    Default: t2.small.search

  AvailabilityZone:
    Type: String
    Default: us-east-1a

  CidrBlock:
    Type: String
    Default: 10.0.0.0/24

  GroupDescription:
    Type: String
    Default: HW2 open search security group

  SGName:
    Type: String
    Default: hw2-security-group

Resources:

  OpenSearchServiceDomain:
    Type: 'AWS::OpenSearchService::Domain'
    Properties:
      DomainName:
        Ref: DomainName
      EngineVersion:
        Ref: EngineVersion
      ClusterConfig:
        InstanceCount: '2'
        InstanceType:
          Ref: InstanceType
      EBSOptions:
        EBSEnabled: true
        Iops: '0'
        VolumeSize: '10'
        VolumeType: 'gp2'
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: true
        override_main_response_version: true
      Tags:
        - Key: project
          Value: hw2
      VPCOptions:
        SubnetIds:
          - Ref: subnet
        SecurityGroupIds:
          - Ref: securityGroup

  vpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: hw2-vpc
        - Key: project
          Value: hw2

  subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: vpc
      CidrBlock:
        Ref: CidrBlock
      AvailabilityZone:
        Ref: AvailabilityZone
      Tags:
        - Key: Name
          Value: hw2-subnet
        - Key: project
          Value: hw2

  securityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription:
        Ref: GroupDescription
      VpcId:
        Ref: vpc
      GroupName:
        Ref: SGName
      SecurityGroupIngress:
        - FromPort: 443
          IpProtocol: tcp
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value:
            Ref: SGName
        - Key: project
          Value: hw2

  HW2PhotosBucket:
    Type: AWS::S3::Bucket
    DependsOn: HW2TriggerIndexPhotosLambdaPermission
    Properties:
      BucketName: 'hw2-1323-photos'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt HW2IndexPhotosLambda.Arn
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .jpeg

  HW2TriggerIndexPhotosLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt HW2IndexPhotosLambda.Arn
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::hw2-1323-photos'
      SourceAccount: !Ref AWS::AccountId

  HW2LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: hw2-lambda-function-execution-role
      Description: Describe this IAM role here
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: '/'
      Policies:
      - PolicyName: hw2-admin-access-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"

  HW2IndexPhotosLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Uses AWS Rekognition to scan photos uploaded to S3 bucket
      FunctionName: hw2-index-photos-function
      Runtime: python3.8
      Role: !GetAtt HW2LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from hw2-index-photos-function!')
              }
      Handler: index_photos_function.lambda_handler
      MemorySize: 256
      Timeout: 10

  HW2SearchPhotosLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Search for photos in Open Search domain
      FunctionName: hw2-search-photos-function
      Runtime: python3.8
      Role: !GetAtt HW2LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from hw2-search-photos-function!')
              }
      Handler: search_photos_function.lambda_handler
      MemorySize: 256
      Timeout: 10

  HW2RestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: hw2-api-gateway
      Description: An api gateway with S3 service integrations
      ApiKeySourceType: HEADER
      BinaryMediaTypes:
        - '*/*'
      EndpointConfiguration:
        Types:
        - REGIONAL
      Tags:
        - Key: project
          Value: hw2
        - Key: account
          Value: 1323

  HW2RestAPISearchResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt HW2RestAPI.RootResourceId
      PathPart: 'search'
      RestApiId: !Ref HW2RestAPI

  HW2RestAPISearchGETMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref HW2RestAPISearchResource
      RestApiId: !Ref HW2RestAPI
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !Join
              - ''
              - - 'arn:aws:lambda:'
                - !Ref AWS::Region
                - ':'
                - !Ref AWS::AccountId
                - ':function:hw2-search-photos-function'
        Credentials: !GetAtt HW2RestAPIIamRole.Arn
        IntegrationResponses:
          - SelectionPattern: ''
            StatusCode: 200
      MethodResponses:
        - StatusCode: 200

  HW2RestAPIPhotosResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt HW2RestAPI.RootResourceId
      PathPart: 'photos'
      RestApiId: !Ref HW2RestAPI

  HW2RestAPIFolderResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref HW2RestAPIPhotosResource
      PathPart: '{folder}'
      RestApiId: !Ref HW2RestAPI

  HW2RestAPIObjectResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref HW2RestAPIFolderResource
      PathPart: '{object}'
      RestApiId: !Ref HW2RestAPI

  HW2RestAPIPhotosPUTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: PUT
      ResourceId: !Ref HW2RestAPIObjectResource
      RestApiId: !Ref HW2RestAPI
      RequestParameters:
        method.request.path.folder: true
        method.request.path.object: true
      Integration:
        IntegrationHttpMethod: PUT
        Type: AWS
        RequestParameters:
          integration.request.path.bucket: method.request.path.folder
          integration.request.path.key: method.request.path.object
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:s3:path/{bucket}/{key}'
        ConnectionType: INTERNET
        Credentials: !GetAtt HW2RestAPIIamRole.Arn
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        IntegrationResponses:
          - SelectionPattern: ''
            StatusCode: 200
            ContentHandling: CONVERT_TO_TEXT
          - SelectionPattern: 400
            StatusCode: 400
            ContentHandling: CONVERT_TO_TEXT
          - SelectionPattern: 500
            StatusCode: 500
            ContentHandling: CONVERT_TO_TEXT
      MethodResponses:
        - StatusCode: 200
        - StatusCode: 400
        - StatusCode: 500

  HW2RestAPIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: v1
      Description: HW2 API Stage v0
      DeploymentId: !Ref HW2RestAPIDeployment
      RestApiId: !Ref HW2RestAPI
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          LoggingLevel: INFO   # VALID VALUES ARE OFF, ERROR and INFO
          DataTraceEnabled: true
          MetricsEnabled: false

  HW2RestAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: HW2RestAPIPhotosPUTMethod
    Properties:
      Description: HW2 API Deployment
      RestApiId: !Ref HW2RestAPI

  HW2RestAPIIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: hw2-api-gateway-role
      Description: Allows API Gateway to push logs to CloudWatch Logs and put binary objects to an S3 bucket.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: 'Allow'
            Principal:
              Service:
                - 'apigateway.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Policies:
        - PolicyName: hw2-api-gateway-s3-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: s3:PutObject
              Resource: arn:aws:s3:::hw2-1323-photos/*

  HW2RestAPIIamPolicy:
    Type: 'AWS::IAM::Policy'
    DependsOn: HW2RestAPIIamRole
    Properties:
      PolicyName: hw2-api-gateway_lambda_policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 'lambda:InvokeFunction'
            Resource: '*'
      Roles:
        - Ref: HW2RestAPIIamRole

Outputs:
  HW2PhotosBucketARN:
    Description: 'The ARN for the hw2-1323-photos bucket'
    Value: !GetAtt HW2PhotosBucket.Arn
