version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo "Capturing the AWS CLI and Python versions used in the build."
            - aws --version
            - python --version
    pre_build:
        commands:
            - echo "Installing 3rd party Python modules"
            - pip install -r requirements.txt
    build:
        commands:
            - echo Building hw2 lambdas - started on `date`
            - zip -r -j index_photos_function.zip src/index_photos_function.py
            - zip -r -j search_photos_function.zip src/search_photos_function.py
    post_build:
        commands:
            - echo Build completed on `date`
            - echo "Updating lambda function code."
            - aws lambda update-function-code --function-name "hw2-index-photos-function" --zip-file fileb://./index_photos_function.zip
            - aws lambda update-function-code --function-name "hw2-search-photos-function" --zip-file fileb://./search_photos_function.zip

# REFERENCE:
#   - Build specification reference for CodeBuild
#     https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
